#!/bin/bash
# Finds if S1 is installed, and if so, whcih version


if [ -d  "/Applications/SentinelOne" ]; then
	sentVersion=$(defaults read /Applications/SentinelOne/SentinelOne\ Extensions.app/Contents/Info.plist CFBundleShortVersionString)
else
	sentVersion="Not Installed"
fi

echo "<result>${sentVersion}</result>"
