#!/bin/bash

############################################################################
# Script to prompt users for their first and last names and emails addresses
# Then submits this info to jamf computer record, along with logged in username as well
# Use Parameter $4 in Jamf for the company name, $5 for the email example (yourname@company.com)
#This allows users to cancel the frist screen, say if they are in a meeting or something and will exit the whole script
# Copyright Brooke Burdick
# October 2023
############################################################################

#variables from Jamf script $4 for the company name, $5 for the email example (emailprefix@company.com)
companyName=$4
emailExample=$5


#This is the initial prompt for end user to enter ther info. They can hit cancel, and the script will exit and try again tomorrow (if you have a daily policy run)
osascript -e 'display dialog "'$companyName' needs to update your Mac Inventory Record in Jamf. Please complete the following prompts." with title "Inventory Update Needed" with icon posix file "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/UserUnknownIcon.icns" buttons {"Cancel","Continue"} default button 2 Cancel button 1 
set xxxx to button returned of the result
if xxxx is "Cancel" then
	error number -128
end if' || exit 1


#function for prompting users to get variables
getUserInput()
{
	launchctl asuser $(stat -f %u /dev/console) osascript <<-APPLESCRIPT
	tell app "System Events"
	text returned of (display dialog "$1" default answer "" buttons {"Continue"} default button 1)
	end tell
	APPLESCRIPT
}

#prompt for name and email
realName=$(getUserInput "What is your full name? First Last")
emailAddress=$(getUserInput "What is your full work email address? Example: $emailExample")

# Grab the username of the user that last logged in (current user) for the username field
currentUser=$(defaults read /Library/Preferences/com.apple.loginwindow lastUserName)

#debug checking
echo $currentUser
echo $realName
echo $emailAddress
echo $currentUser

#Send the user's username, full name and email address to the Mac's inventory record. Use double quotes for realName to capture first and last name entered by the user.
/usr/local/bin/jamf recon -realname "$realName"
/usr/local/bin/jamf recon -email $emailAddress
/usr/local/bin/jamf recon -endUsername $currentUser

#thank you message osascript function
thanks='display dialog "Thank you '$realName'! Your computer inventory record has updated in Jamf." with title "Thank you!" with icon posix file "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/ToolbarFavoritesIcon.icns" buttons {"Continue"} default button 1'

#call thanks function
/usr/bin/osascript -e "$thanks"
