#!/bin/bash

################################
# Copyright Brooke Burdick
# October 2023
# Brooburd@gmail.com
# This script will ask for a server name, API username, API password. API user account MUST have read/ write permissions.
# This script will be packaged in Composer and then "installed" to be cached locally (jamf waiting room or path of your choice, and will be deleted after. 
# The point of this script is to make a device show as "unmanaged" before it disconnects from the jamf server so they are easy to identify and search for. If you just send a removeMDM/ removeframework command, the mac still shows in Jamf normally
# then  you want to run another script via policy to kick off this script
################################

#Enter the info for the API calls - this script will be deleted after this is ran for this reason - also recommend rotating the password after a successful run
USERNAME=ENTER YOUR API USERNAME
PASSWORD=ENTER YOUR API PW
JSSURL=ENTER YOUR JSS URL

# Get local serial number
SERIAL=$(system_profiler SPHardwareDataType | awk '/Serial/ {print $4}')
/bin/echo "Serial number is $SERIAL"

# Get JAMF ID of device
JAMF_ID=$(curl -X GET -s -k -u "$USERNAME:$PASSWORD" "$JSSURL/JSSResource/computers/serialnumber/$SERIAL" | xmllint --xpath '/computer/general/id/text()' -)
/bin/echo "JAMF ID for $SERIAL is $JAMF_ID"

#Change device to show Unmanaged in JAMF (this is how we know the script ran since once it is deleted, it no longer checks back in with a success or failure)
# we can now make searches based on unmanaged devices
curl -X PUT -s -k -u "$USERNAME:$PASSWORD" "$JSSURL/JSSResource/computers/id/$JAMF_ID" -H "Content-Type: application/xml" -H "Accept: application/xml" -d '<computer><general><remote_management><managed>false</managed></remote_management></general></computer>'
/bin/echo "Unmanaged"	

#now remove MDM Profiles
sudo jamf removeMdmProfile

#now remove the JAMF Framework
sudo jamf removeframework

#now delete script from the waiting room
#if you packaged it in a different location, update the path there
#FILL IN YOUR PATH HERE IF DIFFERENT
sudo rm -f /Library/Application Support/JAMF/Waiting Room/Jamf_Unmanage_Uninstall.sh

/bin/echo "Done."

exit 0
