#!/bin/bash

################################
# Copyright Brooke Burdick
# October 2023
# Brooburd@gmail.com
# This script will ask for a server name, API username, API password. API user account MUST have read/ write permissions.
# This script will be packaged and then cached locally (jamf waiting room or path of your choice, and will be deleted after. 
# The point of this script is to make a device show as "unmanaged" before it disconnects from the jamf server so they are easy to identify and search for.
# then run another script or file process to kick off the script
################################

#applescript funciton for getting user input
getUserInput()
{
	launchctl asuser $(stat -f %u /dev/console) osascript <<-APPLESCRIPT
	tell app "System Events"
	text returned of (display dialog "$1" default answer "" buttons {"OK"} default button 1)
	end tell
	APPLESCRIPT
}

#get the info for the variables
USERNAME=$(getUserInput "What is the username of the JSS API Account?")
PASSWORD=(getUserInput "What is the password of the JSS API Account?")
JSSURL=$(getUserInput "What is the URL of the client Jamf Server? (Must be the FULL name of the jamf URL: https://name.jamfcloud.com"))

# Get local serial number
SERIAL=$(system_profiler SPHardwareDataType | awk '/Serial/ {print $4}')
/bin/echo "Serial number is $SERIAL"

# Get JAMF ID of device
JAMF_ID=$(curl -X GET -s -k -u "$USERNAME:$PASSWORD" "$JSSURL/JSSResource/computers/serialnumber/$SERIAL" | xmllint --xpath '/computer/general/id/text()' -)
/bin/echo "JAMF ID for $SERIAL is $JAMF_ID"

#Change device to show Unmanaged in JAMF (this is how we know the script ran since once it is deleted, it no longer checks back in with a success or failure)
# we can now make searches based on unmanaged devices
curl -X PUT -s -k -u "$USERNAME:$PASSWORD" "$JSSURL/JSSResource/computers/id/$JAMF_ID" -H "Content-Type: application/xml" -H "Accept: application/xml" -d '<computer><general><remote_management><managed>false</managed></remote_management></general></computer>'
/bin/echo "Unmanaged"	

#now remove MDM Profiles
sudo jamf removeMdmProfile
/bin/echo "Removed MDM"

#now remove the JAMF Framework
sudo jamf removeframework
/bin/echo "Removed Framework"

#now delete script from the waiting room
#if you packaged it in a different locaiton, update the path there
#FILL IN YOUR PATH HERE IF DIFFERENT
sudo rm -f /Library/Application Support/JAMF/Waiting Room/Jamf_Unmanage_Uninstall.sh

/bin/echo "Done."

exit 0
