#!/bin/bash

# Get the Serial Number of the Machine
sn=$(system_profiler SPHardwareDataType | awk '/Serial/ {print $4}')
echo $sn

# Set the ComputerName, HostName and LocalHostName
scutil --set ComputerName $sn
scutil --set HostName $sn
scutil --set LocalHostName $sn

#set the name via Jamf as well
/usr/local/bin/jamf SetComputername -name $sn

echo "Renamed to $sn"
