#!/bin/bash

##############################################################################
# This script renames Macs to the full name user's macbookpro
# This is to overrite and Macs with identical names
# Brooke Burdick
# Brooburd@gmail.com
# October 2023
##############################################################################

#Grab the full name of the user
currentUser=$(id -P $(stat -f%Su /dev/console) | awk -F '[:]' '{print $8}')
echo $currentUser

#gather the model id of the computer
model=$(/usr/sbin/system_profiler SPHardwareDataType | grep "Model Name" |  awk -F  ':' '{print $2}')
echo $model

# Create a string for computer name
comp_name="${currentUser} ${model}"
echo $comp_name

#rename locally for good measure
scutil --set ComputerName $comp_name
scutil --set HostName $comp_name
scutil --set LocalHostName $comp_name

# Rename the Mac using the jamf command line tool
/usr/local/bin/jamf SetComputername -name "$comp_name"      

echo "Renamed to $comp_name"
