#!/bin/bash

############################################################################
# This script fills out the "username" tab under Jamf User&Location Inventory records based on logged in username
# Copyright Brooke Burdick
# October 2023
############################################################################

# Grab the username of the user that last logged in (current user) for the username field
currentUser=$(defaults read /Library/Preferences/com.apple.loginwindow lastUserName)

#debug checking
echo $currentUser

#Send the user's username to the Mac's inventory record.
/usr/local/bin/jamf recon -endUsername $currentUser

exit 0
